---
- hosts: node
  remote_user: root
  gather_facts: no
  
  tasks:

  - name: 安装epel源
    yum: name=epel-release  state=latest
#    tags: 1  

  - name: 安装net-tools tree nmap lrzsz dos2unix telnet screen vim lsof wget ntp rsync
    yum:
      name:
        - net-tools
        - tree
        - nmap
        - lrzsz
        - dos2unix
        - telnet
        - screen
        - vim
        - lsof
        - wget
        - ntp
        - rsync
      state: installed
#    tags: 2

  - name: 关闭防火墙
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: 关闭selinux
    shell:
      cmd: setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config 
#    tags: stop_selinux

  - name: 修改内核参数
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      ignoreerrors: yes
      #state: present
    with_items:
      - { name: 'net.ipv6.conf.all.disable_ipv6', value: 1 }
      - { name: 'net.ipv6.conf.default.disable_ipv6', value: 1 }
      # 避免放大攻击
      - { name: 'net.ipv4.icmp_echo_ignore_broadcasts', value: 1 }
      # 开启恶意icmp错误消息保护
      - { name: 'net.ipv4.icmp_ignore_bogus_error_responses', value: 1 }
      # 不充当路由器
      - { name: 'net.ipv4.ip_forward', value: 0 }
      - { name: 'net.ipv4.conf.all.send_redirects', value: 0 }
      - { name: 'net.ipv4.conf.default.send_redirects', value: 0 }
      # 开启反向路径过滤
      - { name: 'net.ipv4.conf.all.rp_filter', value: 1 }
      - { name: 'net.ipv4.conf.default.rp_filter', value: 1 }
      # 处理无源路由的包
      - { name: 'net.ipv4.conf.all.accept_source_route', value: 0 }
      - { name: 'net.ipv4.conf.default.accept_source_route', value: 0 }
      # 开启SYN洪水攻击保护
      - { name: 'net.ipv4.tcp_syncookies', value: 1 }
      # TIME_WAIT套接字的最大数量
      - { name: 'net.ipv4.tcp_max_tw_buckets', value: 6000 }
      # 关闭tcp_sack 对于广域网通信来说这个选项应该启用
      - { name: 'net.ipv4.tcp_sack', value: 1 }
      # 要支持超过 64KB 的窗口，必须启用该值
      - { name: 'net.ipv4.tcp_window_scaling', value: 1 }
      #为自动调优定义每个 socket 使用的内存
      - { name: 'net.ipv4.tcp_rmem', value: 4096 87380 4194304 }
      - { name: 'net.ipv4.tcp_wmem', value: 4096 16384 4194304 }
      - { name: 'net.core.wmem_default', value: 8388608 }
      - { name: 'net.core.rmem_default', value: 8388608 }
      - { name: 'net.core.rmem_max', value: 16777216 }
      - { name: 'net.core.wmem_max', value: 16777216 }
      #该参数决定了，网络设备接收数据包的速率比内核处理这些包的速率快时，允许送到队列的数据包的最大数目。
      - { name: 'net.core.netdev_max_backlog ', value: 262144 }
      - { name: 'net.ipv4.tcp_max_orphans', value: 3276800 }
      - { name: 'net.ipv4.tcp_max_syn_backlog', value: 262144 }
      - { name: 'net.ipv4.tcp_timestamps', value: 0 }
      - { name: 'net.ipv4.tcp_synack_retries', value: 1 }
      - { name: 'net.ipv4.tcp_syn_retries', value: 1 }
      - { name: 'net.ipv4.tcp_tw_recycle', value: 1 }
      - { name: 'net.ipv4.tcp_tw_reuse', value: 1 }
      - { name: 'net.ipv4.tcp_mem', value: 94500000 915000000 927000000 }
      - { name: 'net.ipv4.tcp_fin_timeout', value: 1 }
      - { name: 'net.ipv4.tcp_keepalive_time', value: 30 }
      - { name: 'fs.file-max', value: 265535 }
      - { name: 'net.ipv4.conf.all.accept_redirects', value: 0 }
      - { name: 'net.ipv4.conf.default.accept_redirects', value: 0 }
      - { name: 'net.ipv4.conf.all.secure_redirects', value: 0 }
      - { name: 'net.ipv4.conf.default.secure_redirects', value: 0 }
      - { name: 'vm.swappiness', value: 10 }
      - { name: 'kernel.sysrq', value: 0 }
      - { name: 'kernel.core_uses_pid', value: 1 }
      - { name: 'kernel.msgmnb', value: 65536 }
      - { name: 'kernel.msgmax', value: 65536 }
      - { name: 'kernel.shmmax', value: 68719476736 }
      - { name: 'kernel.shmall', value: 4294967296 }
    tags: kern
 
  - name: 传递zabbix_agent脚本
    copy:
      src: /root/zabagentd.sh
      dest: /root/zabagentd.sh
      mode: u=rwx,g=r,o=g
    tags: zabbix_agent


  - name: 执行安装zabbix_agent脚本
    shell: 
      cmd: bash zabagentd.sh
      chdir: /root
#    tags: bash_zabbix

